/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pokecoin);
  }
}(this, function(expect, Pokecoin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pokecoin.PropertiesAttacksItems();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PropertiesAttacksItems', function() {
    it('should create an instance of PropertiesAttacksItems', function() {
      // uncomment below and update the code to test PropertiesAttacksItems
      //var instance = new Pokecoin.PropertiesAttacksItems();
      //expect(instance).to.be.a(Pokecoin.PropertiesAttacksItems);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Pokecoin.PropertiesAttacksItems();
      //expect(instance).to.be();
    });

    it('should have the property cost (base name: "cost")', function() {
      // uncomment below and update the code to test the property cost
      //var instance = new Pokecoin.PropertiesAttacksItems();
      //expect(instance).to.be();
    });

    it('should have the property convertedEnergyCost (base name: "convertedEnergyCost")', function() {
      // uncomment below and update the code to test the property convertedEnergyCost
      //var instance = new Pokecoin.PropertiesAttacksItems();
      //expect(instance).to.be();
    });

    it('should have the property damage (base name: "damage")', function() {
      // uncomment below and update the code to test the property damage
      //var instance = new Pokecoin.PropertiesAttacksItems();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new Pokecoin.PropertiesAttacksItems();
      //expect(instance).to.be();
    });

  });

}));
