/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddBlockBody model module.
 * @module model/AddBlockBody
 * @version 1.5.4
 */
class AddBlockBody {
    /**
     * Constructs a new <code>AddBlockBody</code>.
     * The body schema for adding a block
     * @alias module:model/AddBlockBody
     * @param previousHash {String} 
     * @param data {String} 
     * @param timestamp {Number} 
     * @param nonce {Number} 
     */
    constructor(previousHash, data, timestamp, nonce) { 
        
        AddBlockBody.initialize(this, previousHash, data, timestamp, nonce);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, previousHash, data, timestamp, nonce) { 
        obj['previousHash'] = previousHash;
        obj['data'] = data;
        obj['timestamp'] = timestamp;
        obj['nonce'] = nonce;
    }

    /**
     * Constructs a <code>AddBlockBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddBlockBody} obj Optional instance to populate.
     * @return {module:model/AddBlockBody} The populated <code>AddBlockBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddBlockBody();

            if (data.hasOwnProperty('previousHash')) {
                obj['previousHash'] = ApiClient.convertToType(data['previousHash'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('nonce')) {
                obj['nonce'] = ApiClient.convertToType(data['nonce'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddBlockBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddBlockBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddBlockBody.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['previousHash'] && !(typeof data['previousHash'] === 'string' || data['previousHash'] instanceof String)) {
            throw new Error("Expected the field `previousHash` to be a primitive type in the JSON string but got " + data['previousHash']);
        }
        // ensure the json data is a string
        if (data['data'] && !(typeof data['data'] === 'string' || data['data'] instanceof String)) {
            throw new Error("Expected the field `data` to be a primitive type in the JSON string but got " + data['data']);
        }

        return true;
    }


}

AddBlockBody.RequiredProperties = ["previousHash", "data", "timestamp", "nonce"];

/**
 * @member {String} previousHash
 */
AddBlockBody.prototype['previousHash'] = undefined;

/**
 * @member {String} data
 */
AddBlockBody.prototype['data'] = undefined;

/**
 * @member {Number} timestamp
 */
AddBlockBody.prototype['timestamp'] = undefined;

/**
 * @member {Number} nonce
 */
AddBlockBody.prototype['nonce'] = undefined;






export default AddBlockBody;

