/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Block from './Block';

/**
 * The AddBlockErrorResponse model module.
 * @module model/AddBlockErrorResponse
 * @version 1.5.4
 */
class AddBlockErrorResponse {
    /**
     * Constructs a new <code>AddBlockErrorResponse</code>.
     * The error response schema for failed block adding
     * @alias module:model/AddBlockErrorResponse
     */
    constructor() { 
        
        AddBlockErrorResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddBlockErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddBlockErrorResponse} obj Optional instance to populate.
     * @return {module:model/AddBlockErrorResponse} The populated <code>AddBlockErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddBlockErrorResponse();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('block')) {
                obj['block'] = Block.constructFromObject(data['block']);
            }
            if (data.hasOwnProperty('lastBlock')) {
                obj['lastBlock'] = Block.constructFromObject(data['lastBlock']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddBlockErrorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddBlockErrorResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field `block`
        if (data['block']) { // data not null
          Block.validateJSON(data['block']);
        }
        // validate the optional field `lastBlock`
        if (data['lastBlock']) { // data not null
          Block.validateJSON(data['lastBlock']);
        }

        return true;
    }


}



/**
 * @member {module:model/AddBlockErrorResponse.CodeEnum} code
 */
AddBlockErrorResponse.prototype['code'] = undefined;

/**
 * @member {String} message
 */
AddBlockErrorResponse.prototype['message'] = undefined;

/**
 * @member {module:model/Block} block
 */
AddBlockErrorResponse.prototype['block'] = undefined;

/**
 * @member {module:model/Block} lastBlock
 */
AddBlockErrorResponse.prototype['lastBlock'] = undefined;





/**
 * Allowed values for the <code>code</code> property.
 * @enum {String}
 * @readonly
 */
AddBlockErrorResponse['CodeEnum'] = {

    /**
     * value: "BlockIsNotValidError"
     * @const
     */
    "BlockIsNotValidError": "BlockIsNotValidError"
};



export default AddBlockErrorResponse;

