/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PokemonCard from './PokemonCard';

/**
 * The BuyDefaultPackageSchemaResponse model module.
 * @module model/BuyDefaultPackageSchemaResponse
 * @version 1.5.4
 */
class BuyDefaultPackageSchemaResponse {
    /**
     * Constructs a new <code>BuyDefaultPackageSchemaResponse</code>.
     * Buy a default cardpackage and receive an array of bought cards
     * @alias module:model/BuyDefaultPackageSchemaResponse
     */
    constructor() { 
        
        BuyDefaultPackageSchemaResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BuyDefaultPackageSchemaResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BuyDefaultPackageSchemaResponse} obj Optional instance to populate.
     * @return {module:model/BuyDefaultPackageSchemaResponse} The populated <code>BuyDefaultPackageSchemaResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BuyDefaultPackageSchemaResponse();

            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], [PokemonCard]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BuyDefaultPackageSchemaResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BuyDefaultPackageSchemaResponse</code>.
     */
    static validateJSON(data) {
        if (data['cards']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cards'])) {
                throw new Error("Expected the field `cards` to be an array in the JSON data but got " + data['cards']);
            }
            // validate the optional field `cards` (array)
            for (const item of data['cards']) {
                PokemonCard.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/PokemonCard>} cards
 */
BuyDefaultPackageSchemaResponse.prototype['cards'] = undefined;






export default BuyDefaultPackageSchemaResponse;

