/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PokemonCard from './PokemonCard';

/**
 * The CardPack model module.
 * @module model/CardPack
 * @version 1.5.4
 */
class CardPack {
    /**
     * Constructs a new <code>CardPack</code>.
     * A pack of cards. Formerly known as Booster.
     * @alias module:model/CardPack
     * @param name {String} 
     * @param cards {Array.<module:model/PokemonCard>} 
     */
    constructor(name, cards) { 
        
        CardPack.initialize(this, name, cards);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, cards) { 
        obj['name'] = name;
        obj['cards'] = cards;
    }

    /**
     * Constructs a <code>CardPack</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardPack} obj Optional instance to populate.
     * @return {module:model/CardPack} The populated <code>CardPack</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardPack();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], [PokemonCard]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CardPack</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CardPack</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CardPack.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['cards']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cards'])) {
                throw new Error("Expected the field `cards` to be an array in the JSON data but got " + data['cards']);
            }
            // validate the optional field `cards` (array)
            for (const item of data['cards']) {
                PokemonCard.validateJsonObject(item);
            };
        }

        return true;
    }


}

CardPack.RequiredProperties = ["name", "cards"];

/**
 * @member {String} name
 */
CardPack.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/PokemonCard>} cards
 */
CardPack.prototype['cards'] = undefined;






export default CardPack;

