/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangePasswordBody model module.
 * @module model/ChangePasswordBody
 * @version 1.5.4
 */
class ChangePasswordBody {
    /**
     * Constructs a new <code>ChangePasswordBody</code>.
     * The body to change a password of an user
     * @alias module:model/ChangePasswordBody
     * @param password {String} 
     * @param newPassword {String} 
     */
    constructor(password, newPassword) { 
        
        ChangePasswordBody.initialize(this, password, newPassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password, newPassword) { 
        obj['password'] = password;
        obj['newPassword'] = newPassword;
    }

    /**
     * Constructs a <code>ChangePasswordBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangePasswordBody} obj Optional instance to populate.
     * @return {module:model/ChangePasswordBody} The populated <code>ChangePasswordBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangePasswordBody();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('newPassword')) {
                obj['newPassword'] = ApiClient.convertToType(data['newPassword'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChangePasswordBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChangePasswordBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ChangePasswordBody.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['newPassword'] && !(typeof data['newPassword'] === 'string' || data['newPassword'] instanceof String)) {
            throw new Error("Expected the field `newPassword` to be a primitive type in the JSON string but got " + data['newPassword']);
        }

        return true;
    }


}

ChangePasswordBody.RequiredProperties = ["password", "newPassword"];

/**
 * @member {String} password
 */
ChangePasswordBody.prototype['password'] = undefined;

/**
 * @member {String} newPassword
 */
ChangePasswordBody.prototype['newPassword'] = undefined;






export default ChangePasswordBody;

