/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pokecoin);
  }
}(this, function(expect, Pokecoin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pokecoin.CardsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CardsApi', function() {
    describe('cardsCardIdGet', function() {
      it('should call cardsCardIdGet successfully', function(done) {
        //uncomment below and update the code to test cardsCardIdGet
        //instance.cardsCardIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsGet', function() {
      it('should call cardsGet successfully', function(done) {
        //uncomment below and update the code to test cardsGet
        //instance.cardsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsPackagesCardPackNameBuyDefaultPackageGet', function() {
      it('should call cardsPackagesCardPackNameBuyDefaultPackageGet successfully', function(done) {
        //uncomment below and update the code to test cardsPackagesCardPackNameBuyDefaultPackageGet
        //instance.cardsPackagesCardPackNameBuyDefaultPackageGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsPackagesCardPackNameGet', function() {
      it('should call cardsPackagesCardPackNameGet successfully', function(done) {
        //uncomment below and update the code to test cardsPackagesCardPackNameGet
        //instance.cardsPackagesCardPackNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsPackagesCurrentPackageCostGet', function() {
      it('should call cardsPackagesCurrentPackageCostGet successfully', function(done) {
        //uncomment below and update the code to test cardsPackagesCurrentPackageCostGet
        //instance.cardsPackagesCurrentPackageCostGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsPackagesGet', function() {
      it('should call cardsPackagesGet successfully', function(done) {
        //uncomment below and update the code to test cardsPackagesGet
        //instance.cardsPackagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsUsercardsGet', function() {
      it('should call cardsUsercardsGet successfully', function(done) {
        //uncomment below and update the code to test cardsUsercardsGet
        //instance.cardsUsercardsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
